#!/usr/bin/env python
Import('env')

module_env = env.Clone()
module_env.add_source_files(env.modules_sources, "*.cpp")

module_env.Append(CPPPATH=["."])

env.Append(LIBPATH=[Dir('lib').abspath])
env.Append(LIBS=['WOWConnectManaged'])
# env.Append(LIBS=['WOWConnect'])
