extends Node

signal twist(screen:int,direction:int)
signal tap(count:int)
signal shake_tile_elements(tile : Array, direction : Vector3)
signal reveal_fragment(id:int)
signal fragment_collected(id:int)
signal cube_disconnected()
signal app_connected(msg:String)
signal cube_connected(msg:String)
signal send_msg_to_cube(msg:String, val:int)
signal error()
signal play_gravestone_animation(msg:String)
signal animate_skeletree(msg:String)
signal activate_speaker(id:String)
signal deactivate_speaker(id:String)
signal activate_nearby_speaker(id:String)
signal skeletree_state2(msg)
signal all_frags_collected()
signal final()
signal select_mode(type : bool)
